# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-2019

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'install -g Wyam.Tool'

- script: git clone https://github.com/ssa3512/ssa3512.github.io output
  displayName: "Clone existing output"

- script: wyam
  displayName: "Run wyam build"